Q1.Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 

In [78]:
import pandas as pd
import numpy as np


try:
        def vandermonde_matrix(a,n):
                 return np.vander(a,n,increasing=True)
        print("Matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde:\n",vandermonde_matrix(np.array([1,2,3]),4))    

except:
       print("Error while reading input")  
        
        
       

Matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde:
 [[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]


Q2.Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [79]:
try:

      def moving_avg(a,w):
              df=pd.DataFrame(a,columns=['input'])
              df['op'] = df.input.rolling(window=w).mean() # to find avg with window size
              df=df.dropna()
              output=np.array(df['op']).astype('int64')
              print( "Moving AVG of given array with window %i:" %w,output)
      moving_avg( np.array( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]),3)
except:
    print("Error while reading input")

Moving AVG of given array with window 3: [  5   4   5   6   9  28  49  72  84  93 116]
